apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"] # actions on resources, create, read, update, delete.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop
subjects:
- kind: User
  name: ramesh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: v1
# data:
#   mapRoles: |
#     - groups:
#       - system:bootstrappers
#       - system:nodes
#       rolearn: arn:aws:iam::076583563305:role/eksctl-eks-spot-cluster-nodegroup--NodeInstanceRole-F90wd24m02pO
#       username: system:node:{{EC2PrivateDNSName}}
#   mapUsers: |
#     - groups:
#       - roboshop-admin
#       userarn: arn:aws:iam::076583563305:user/ramesh
#       username: ramesh
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2024-03-02T08:03:55Z"
#   name: aws-auth
#   namespace: kube-system
#   resourceVersion: "1271" 
#   uid: 09e216ea-5669-4838-a5ab-5cf5f75fef6b
